name: Deploy code to staging or production

on:
  push:
    branches: [staging, production]

jobs:
  validateActor:
    runs-on: ubuntu-latest
    outputs:
      IS_VALID: ${{ fromJSON(steps.isAuthorDeployer.outputs.isTeamMember) || fromJSON(steps.isMergerDeployer.outputs.isTeamMember) || steps.getMergedPullRequest.outputs.author == 'OSBotify' }}

    steps:
      - name: Get merged pull request
        id: getMergedPullRequest
        # TODO: Point back action actions-ecosystem after https://github.com/actions-ecosystem/action-get-merged-pull-request/pull/223 is merged
        uses: roryabraham/action-get-merged-pull-request@7a7a194f6ff8f3eef58c822083695a97314ebec1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if PR author is a deployer
        id: isAuthorDeployer
        uses: tspascoal/get-user-teams-membership@baf2e6adf4c3b897bd65a7e3184305c165aec872
        with:
          GITHUB_TOKEN: ${{ secrets.OS_BOTIFY_TOKEN }}
          username: ${{ steps.getMergedPullRequest.outputs.author }}
          team: mobile-deployers

      - name: Check if PR merger is a deployer
        id: isMergerDeployer
        uses: tspascoal/get-user-teams-membership@baf2e6adf4c3b897bd65a7e3184305c165aec872
        with:
          GITHUB_TOKEN: ${{ secrets.OS_BOTIFY_TOKEN }}
          username: ${{ github.actor }}
          team: mobile-deployers

  deployStaging:
    runs-on: ubuntu-latest
    needs: validateActor
    if: ${{ fromJSON(needs.validateActor.outputs.IS_VALID) && github.ref == 'refs/heads/staging' }}

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: staging
          token: ${{ secrets.OS_BOTIFY_TOKEN }}

      - name: Decrypt Botify GPG key
        run: cd .github/workflows && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output OSBotify-private-key.asc OSBotify-private-key.asc.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Import Botify GPG Key
        run: cd .github/workflows && gpg --import OSBotify-private-key.asc

      - name: Set up git for Botify
        run: |
          git config user.signingkey DBF63700F60F5530
          git config commit.gpgsign true
          git config user.name OSBotify
          git config user.email infra+osbotify@expensify.com


      - name: Tag version
        run: git tag $(npm run print-version --silent)

      - name: 🚀 Push tags to trigger staging deploy 🚀
        run: git push --tags

  deployProduction:
    runs-on: ubuntu-latest
    needs: validateActor
    if: ${{ fromJSON(needs.validateActor.outputs.IS_VALID) && github.ref == 'refs/heads/production' }}

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0
          token: ${{ secrets.OS_BOTIFY_TOKEN }}

      - name: Decrypt Botify GPG key
        run: cd .github/workflows && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output OSBotify-private-key.asc OSBotify-private-key.asc.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Import Botify GPG Key
        run: cd .github/workflows && gpg --import OSBotify-private-key.asc

      - name: Set up git for Botify
        run: |
          git config user.signingkey DBF63700F60F5530
          git config commit.gpgsign true
          git config user.name OSBotify
          git config user.email infra+osbotify@expensify.com


      - name: Checkout production branch
        run: git checkout production

      - name: Get current app version
        run: echo "PRODUCTION_VERSION=$(npm run print-version --silent)" >> $GITHUB_ENV

      - name: Get Release Pull Request List
        id: getReleasePRList
        uses: Expensify/App/.github/actions/getDeployPullRequestList@main
        with:
          TAG: ${{ env.PRODUCTION_VERSION }}
          GITHUB_TOKEN: ${{ secrets.OS_BOTIFY_TOKEN }}
          IS_PRODUCTION_DEPLOY: true

      - name: Generate Release Body
        id: getReleaseBody
        uses: Expensify/App/.github/actions/getReleaseBody@main
        with:
          PR_LIST: ${{ steps.getReleasePRList.outputs.PR_LIST }}

      - name: 🚀 Create release to trigger production deploy 🚀
        uses: softprops/action-gh-release@affa18ef97bc9db20076945705aba8c516139abd
        with:
          tag_name: ${{ env.PRODUCTION_VERSION }}
          body: ${{ steps.getReleaseBody.outputs.RELEASE_BODY }}

        env:
          GITHUB_TOKEN: ${{ secrets.OS_BOTIFY_TOKEN }}
