name: Verify Podfile

on:
    pull_request:
        types: [opened, synchronize]
        branches-ignore: [staging, production]

jobs:
    verify:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '14.x'

            - name: Install node packages
              uses: nick-invision/retry@7c68161adf97a48beb850a595b8784ec57a98cbb
              with:
                  timeout_minutes: 10
                  max_attempts: 5
                  command: npm ci

            - name: Install cocoapods
              uses: nick-invision/retry@7c68161adf97a48beb850a595b8784ec57a98cbb
              with:
                timeout_minutes: 15
                max_attempts: 3
                command: cd ios && pod install

            - run: ./.github/scripts/verifyPodfile.sh
