name: Build and Deploy Web

# This workflow is run when any tag is published
on:
    push:
# TODO - undo changes, this is currently for testing

jobs:
    build:
        runs-on: ubuntu-16.04

        steps:
            - uses: actions/checkout@v2

            # Installs node
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '14.x'

            # Install python pre-reqs
            - name: Setup python
              run: |
                    sudo add-apt-repository ppa:deadsnakes/ppa
                    sudo apt-get update
                    sudo apt install python3.6
                    sudo python3.6 -m pip install --upgrade pip

            # Installs Cloudflare CLI, after installing/upgrading dependencies
            - name: Setup Cloudflare CLI
              run: |
                   # ensure setuptools is updated to latest pip3 version
                   sudo pip3 install -U setuptools
                   # need wheel before cloudflare, this is the only way to ensure order.
                   sudo pip3 install wheel
                   sudo pip3 install cloudflare
