name: Build and Deploy Web

# This workflow is run when any tag is published
on:
    push:
# TODO - undo changes, this is currently for testing

jobs:
    build:
        runs-on: ubuntu-16.04

        steps:
            - uses: actions/checkout@v2

            # Installs node
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '14.x'

            # Install python pre-reqs
            - name: Setup python
              run: sudo apt-get install python3-pip

            # Installs Cloudflare CLI, after installing/upgrading dependencies
            - name: Setup Cloudflare CLI
              run: |
                   pip3 install --upgrade pip setuptools
                   pip3 install wheel # need wheel before cloudflare, this is the only way to ensure order.
                   pip3 install cloudflare
